#include "YetiApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<YetiApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

YetiApp::YetiApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  YetiApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  YetiApp::associateSyntax(_syntax, _action_factory);
}

YetiApp::~YetiApp()
{
}

// External entry point for dynamic application loading
extern "C" void YetiApp__registerApps() { YetiApp::registerApps(); }
void
YetiApp::registerApps()
{
  registerApp(YetiApp);
}

// External entry point for dynamic object registration
extern "C" void YetiApp__registerObjects(Factory & factory) { YetiApp::registerObjects(factory); }
void
YetiApp::registerObjects(Factory & /*factory*/)
{
}

// External entry point for dynamic syntax association
extern "C" void YetiApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { YetiApp::associateSyntax(syntax, action_factory); }
void
YetiApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
